name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        make -j 100 && ./webserv &
    - name: install seige for stress testing the WebServer
      run: brew install siege
    - name: run stress test
      run: |
        echo $HOME
        touch $HOME/siege-index.html
        siege -b -c=200  -t1M -q 127.0.0.1:8080/siege/siege-index.html
