name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make -j
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: webserver-executable
        path: ./webserv
        retention-days: 1

  test:
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Download Executable
      uses: actions/download-artifact@v4
      with:
        name: webserver-executable
        path: ./
    - name: Make Executable Permissions
      run: |
        chmod +x ./webserv

    - name: Start the Webserver
      run: ./webserv &

    - name: install seige for stress testing the WebServer
      run: brew install siege

    - name: run stress test
      run: |
        touch $HOME/siege-index.html
        result=$(siege -b -c=200 -t1S 127.0.0.1:8080 2>&1 | grep Availability: | awk '{print $2}')

        echo $result%
        if [ $(echo "$result < 100.00" | bc) -eq 1 ]; then
            exit 1
        fi
    - name: CleanUp
      run: pkill webserv || exit 1
  
